name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWFhMjljMDktOTY0YS00ZTg0LTg4MzEtNjAyNmM4ODVmNTJmIiwidGVuYW50X2lkIjoiZDFlZTI1MjU2MGVkOWE3MjY5MzBlYjgxZTI5MmRiNmJhM2E5NTE4ODk4OTU3MmU3MmU0M2VlNDE3OTlhYWY5ZSIsImludGVybmFsX3NlY3JldCI6IjU1Y2I5MTNmLWYzNjAtNDQzZC1hYWY5LTYzNDA2NWUxN2JiNSJ9.pPfrDxpAzk0KbzB6NyF2q5KGtCC_a8NchBjxi60yMqY"

JWT_SECRET="FBSHKFBAWIEFVEWVFWE2342523242@"